import { useState, useEffect, useRef, useCallback } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Toolbar } from "@/components/Toolbar";
import { TextViewer } from "@/components/TextViewer";
import { Sidebar } from "@/components/Sidebar";
import { SearchPanel } from "@/components/SearchPanel";
import { AnnotationToolbar } from "@/components/AnnotationToolbar";
import { sampleDocument } from "@/lib/sampleText";
import { useToast } from "@/hooks/use-toast";
import { queryClient } from "@/lib/queryClient";
import * as api from "@/lib/api";
import type { Annotation, Bookmark, Note, AnnotationType, HighlightColor, LearningFormat } from "@shared/schema";

interface SearchMatch {
  sectionIndex: number;
  matchIndex: number;
  position: number;
  length: number;
}

const SECTION_METADATA: Record<number, {
  complexity?: "abstract" | "conceptual" | "concrete" | "factual";
  contentType?: "procedural" | "spatial" | "mathematical" | "narrative" | "expository" | "mixed";
  keywords?: string[];
  length?: number;
  readingLevel?: "elementary" | "middle" | "high" | "college" | "professional";
}> = sampleDocument.sections.reduce((acc, section) => {
  if (section.id === 1) {
    acc[section.id] = {
      complexity: "conceptual",
      contentType: "expository",
      keywords: ["torque", "moment arm", "rotation"],
      length: section.content.length,
      readingLevel: "college",
    };
  } else if (section.id === 2) {
    acc[section.id] = {
      complexity: "concrete",
      contentType: "narrative",
      keywords: ["applications", "engineering", "examples"],
      length: section.content.length,
      readingLevel: "college",
    };
  } else if (section.id === 3) {
    acc[section.id] = {
      complexity: "abstract",
      contentType: "procedural",
      keywords: ["measurement", "control", "sensors"],
      length: section.content.length,
      readingLevel: "college",
    };
  } else {
    acc[section.id] = {
      length: section.content.length,
    };
  }
  return acc;
}, {} as Record<number, {
  complexity?: "abstract" | "conceptual" | "concrete" | "factual";
  contentType?: "procedural" | "spatial" | "mathematical" | "narrative" | "expository" | "mixed";
  keywords?: string[];
  length?: number;
  readingLevel?: "elementary" | "middle" | "high" | "college" | "professional";
}>);

export default function Reader() {
  const { toast } = useToast();
  const [currentPage, setCurrentPage] = useState(1);
  const [zoom, setZoom] = useState(100);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [isAnnotateMode, setIsAnnotateMode] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [currentSearchResult, setCurrentSearchResult] = useState(0);
  const [searchMatches, setSearchMatches] = useState<SearchMatch[]>([]);
  const [activeTool, setActiveTool] = useState<AnnotationType | null>(null);
  const [activeColor, setActiveColor] = useState<HighlightColor>("yellow");
  const [mediaItems, setMediaItems] = useState<Map<number, { type: "image" | "audio" | "multimodal"; audioUrl?: string; imageUrl?: string }>>(new Map());
  const [recommendations, setRecommendations] = useState<Map<number, { format: LearningFormat; reasoning: string; confidence: number; model: string }>>(new Map());
  const [formatUsage, setFormatUsage] = useState<Map<number, LearningFormat>>(new Map());
  const [quizScores, setQuizScores] = useState<Map<number, number | null>>(new Map());
  const [sessionHistory, setSessionHistory] = useState<Array<{ sectionId: number; formatUsed: LearningFormat; timeSpentMs: number; quizScore: number | null; completed: boolean }>>([]);
  const autoGeneratedSectionsRef = useRef<Set<number>>(new Set());
  const sectionTimerRef = useRef<{ sectionId: number; start: number } | null>(null);
  const requestedRecommendationsRef = useRef<Set<number>>(new Set());
  const formatUsageRef = useRef(formatUsage);
  const quizScoresRef = useRef(quizScores);
  const flushSectionInteractionRef = useRef<((sectionId: number, durationMs: number) => Promise<void>) | null>(null);

  const updateMediaItems = useCallback(
    (sectionId: number, updater: (current?: { type: "image" | "audio" | "multimodal"; audioUrl?: string; imageUrl?: string }) => { type: "image" | "audio" | "multimodal"; audioUrl?: string; imageUrl?: string } | undefined) => {
      setMediaItems((prev) => {
        const map = new Map(prev);
        const current = map.get(sectionId);
        const next = updater(current);
        if (next) {
          map.set(sectionId, next);
        } else {
          map.delete(sectionId);
        }
        return map;
      });
    },
    []
  );

  const updateFormatUsageValue = useCallback((sectionId: number, format: LearningFormat | null) => {
    setFormatUsage((prev) => {
      const map = new Map(prev);
      if (format) {
        map.set(sectionId, format);
      } else {
        map.delete(sectionId);
      }
      return map;
    });
  }, []);

  const totalPages = sampleDocument.sections.length;
  const totalSearchResults = searchMatches.length;
  const currentSection = sampleDocument.sections[currentPage - 1];
  const currentRecommendation = currentSection ? recommendations.get(currentSection.id) : undefined;

  useEffect(() => {
    formatUsageRef.current = formatUsage;
  }, [formatUsage]);

  useEffect(() => {
    quizScoresRef.current = quizScores;
  }, [quizScores]);

  // Fetch data
  const { data: annotations = [] } = useQuery<Annotation[]>({
    queryKey: ["/api/annotations"],
  });

  const { data: bookmarks = [] } = useQuery<Bookmark[]>({
    queryKey: ["/api/bookmarks"],
  });

  const { data: notes = [] } = useQuery<Note[]>({
    queryKey: ["/api/notes"],
  });

  // Mutations
  const createAnnotationMutation = useMutation({
    mutationFn: api.createAnnotation,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/annotations"] });
      toast({
        title: "Annotation created",
        description: "Your annotation has been saved.",
      });
    },
    onError: () => {
      toast({
        title: "Error",
        description: "Failed to create annotation.",
        variant: "destructive",
      });
    },
  });

  const deleteAnnotationMutation = useMutation({
    mutationFn: api.deleteAnnotation,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/annotations"] });
      toast({
        title: "Annotation deleted",
        description: "Your annotation has been removed.",
      });
    },
  });

  const createBookmarkMutation = useMutation({
    mutationFn: api.createBookmark,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/bookmarks"] });
      toast({
        title: "Bookmark created",
        description: "Your bookmark has been saved.",
      });
    },
  });

  const deleteBookmarkMutation = useMutation({
    mutationFn: api.deleteBookmark,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/bookmarks"] });
      toast({
        title: "Bookmark deleted",
        description: "Your bookmark has been removed.",
      });
    },
  });

  const updateNoteMutation = useMutation({
    mutationFn: ({ id, content }: { id: string; content: string }) =>
      api.updateNote(id, content),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/notes"] });
    },
  });

  const recordInteractionMutation = useMutation({
    mutationFn: api.recordInteraction,
  });

  const handlePageChange = (page: number) => {
    const validPage = Math.max(1, Math.min(page, totalPages));
    setCurrentPage(validPage);
  };

  const handleZoomChange = (newZoom: number) => {
    setZoom(Math.max(25, Math.min(500, newZoom)));
  };

  const handleTextSelection = () => {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !activeTool) return;

    const selectedText = selection.toString().trim();
    if (!selectedText) return;

    // Simple annotation without precise offset tracking
    // The text itself is enough for matching in most cases
    if (activeTool === "highlight" || activeTool === "underline" || activeTool === "strikethrough") {
      createAnnotationMutation.mutate({
        type: activeTool,
        pageNumber: currentPage,
        color: activeColor,
        textSelection: {
          start: 0,
          end: selectedText.length,
          text: selectedText,
        },
      });
    } else if (activeTool === "note") {
      const noteContent = prompt("Enter your note:");
      if (noteContent) {
        createAnnotationMutation.mutate({
          type: "note",
          pageNumber: currentPage,
          content: noteContent,
          textSelection: {
            start: 0,
            end: selectedText.length,
            text: selectedText,
          },
        });
      }
    }

    selection.removeAllRanges();
  };

  const handleAnnotationClick = (annotation: Annotation) => {
    setCurrentPage(annotation.pageNumber);
  };

  const handleBookmarkClick = (bookmark: Bookmark) => {
    setCurrentPage(bookmark.pageNumber);
  };

  const handleAnnotationDelete = (id: string) => {
    deleteAnnotationMutation.mutate(id);
  };

  const handleBookmarkDelete = (id: string) => {
    deleteBookmarkMutation.mutate(id);
  };

  const handleBookmarkAdd = (label: string, pageNumber: number) => {
    createBookmarkMutation.mutate({ label, pageNumber });
  };

  const handleNoteUpdate = (content: string) => {
    const noteId = notes[0]?.id || "default";
    updateNoteMutation.mutate({ id: noteId, content });
  };

  const handleNextSearchResult = () => {
    if (totalSearchResults > 0) {
      setCurrentSearchResult((prev) => (prev + 1) % totalSearchResults);
    }
  };

  const handlePrevSearchResult = () => {
    if (totalSearchResults > 0) {
      setCurrentSearchResult((prev) => (prev - 1 + totalSearchResults) % totalSearchResults);
    }
  };

  const handleSearchMatchesFound = useCallback((matches: SearchMatch[]) => {
    setSearchMatches(matches);
    setCurrentSearchResult(0);
  }, []);

  const handleMediaAdd = useCallback(async (sectionId: number, type: "image" | "audio" | "multimodal") => {
    const section = sampleDocument.sections.find((s) => s.id === sectionId);
    if (!section) {
      return;
    }

    updateMediaItems(sectionId, () => ({ type }));
    if (type === "image") {
      updateFormatUsageValue(sectionId, "visual");
    } else if (type === "audio") {
      updateFormatUsageValue(sectionId, "audio");
    } else {
      updateFormatUsageValue(sectionId, "multimodal");
    }

    const sectionText = `${section.title}. ${section.content}`;
    const sentences = section.content.match(/[^.!?]+[.!?]+/g) || [];
    const audioText = sentences.slice(0, 3).join(" ").trim() || section.content.slice(0, 400);

    const generateImage = async (): Promise<boolean> => {
      try {
        toast({
          title: "Generating image...",
          description: "Creating a visual companion for this section.",
        });

        const response = await fetch("/api/text-to-image", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ text: sectionText }),
        });

        if (!response.ok) {
          throw new Error("Failed to generate image");
        }

        const imageBlob = await response.blob();
        const imageUrl = URL.createObjectURL(imageBlob);

        updateMediaItems(sectionId, (current) => ({
          ...(current ?? { type }),
          type: current?.type ?? type,
          imageUrl,
        }));

        toast({
          title: "Image generated",
          description: "Visual explanation is ready.",
        });

        return true;
      } catch (error) {
        console.error("Image generation error:", error);
        toast({
          title: "Error",
          description: "Failed to generate image. Please try again.",
          variant: "destructive",
        });

        if (type === "image") {
          updateMediaItems(sectionId, () => undefined);
          updateFormatUsageValue(sectionId, "text");
        }

        return false;
      }
    };

    const generateAudio = async (): Promise<boolean> => {
      try {
        toast({
          title: "Generating audio...",
          description: "Synthesizing narration for this section.",
        });

        const response = await fetch("/api/text-to-speech", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ text: audioText }),
        });

        if (!response.ok) {
          throw new Error("Failed to generate audio");
        }

        const audioBlob = await response.blob();
        const audioUrl = URL.createObjectURL(audioBlob);

        updateMediaItems(sectionId, (current) => ({
          ...(current ?? { type }),
          type: current?.type ?? type,
          audioUrl,
        }));

        toast({
          title: "Audio generated",
          description: "Narrated explanation is ready.",
        });

        return true;
      } catch (error) {
        console.error("Audio generation error:", error);
        toast({
          title: "Error",
          description: "Failed to generate audio. Please try again.",
          variant: "destructive",
        });

        if (type === "audio") {
          updateMediaItems(sectionId, () => undefined);
          updateFormatUsageValue(sectionId, "text");
        }

        return false;
      }
    };

    if (type === "image") {
      await generateImage();
    } else if (type === "audio") {
      await generateAudio();
    } else {
      const imageSuccess = await generateImage();
      if (!imageSuccess) {
        updateFormatUsageValue(sectionId, "audio");
      }
      const audioSuccess = await generateAudio();
      if (imageSuccess && audioSuccess) {
        updateFormatUsageValue(sectionId, "multimodal");
      } else if (imageSuccess && !audioSuccess) {
        updateFormatUsageValue(sectionId, "visual");
      } else if (!imageSuccess && audioSuccess) {
        updateFormatUsageValue(sectionId, "audio");
      } else {
        updateFormatUsageValue(sectionId, "text");
        updateMediaItems(sectionId, () => undefined);
      }
    }
  }, [toast, updateFormatUsageValue, updateMediaItems]);

  const handleMediaRemove = useCallback((sectionId: number) => {
    updateMediaItems(sectionId, () => undefined);
    updateFormatUsageValue(sectionId, "text");
    toast({
      title: "Media removed",
      description: "The multimedia placeholder has been removed.",
    });
  }, [toast, updateMediaItems, updateFormatUsageValue]);

  const flushSectionInteraction = useCallback(async (sectionId: number, durationMs: number) => {
    // Only record interactions with meaningful duration (at least 100ms)
    if (durationMs < 100) {
      return;
    }

    const roundedDuration = Math.max(Math.round(durationMs), 0);
    const interaction = {
      sectionId,
      formatUsed: formatUsageRef.current.get(sectionId) ?? "text",
      timeSpentMs: roundedDuration,
      quizScore: quizScoresRef.current.get(sectionId) ?? null,
      completed: true,
    } as const;

    setSessionHistory((prev) => [...prev, interaction]);

    try {
      await recordInteractionMutation.mutateAsync({
        ...interaction,
        interactedAt: new Date().toISOString(),
      });
    } catch (error) {
      console.error("Failed to persist interaction", error);
    }
  }, [recordInteractionMutation]);

  useEffect(() => {
    flushSectionInteractionRef.current = flushSectionInteraction;
  }, [flushSectionInteraction]);

  const handleQuizSubmit = useCallback((sectionId: number, score: number) => {
    setQuizScores((prev) => {
      const map = new Map(prev);
      map.set(sectionId, score);
      return map;
    });
  }, []);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
        return;
      }

      if (e.key === "ArrowRight" || e.key === "PageDown") {
        e.preventDefault();
        handlePageChange(currentPage + 1);
      } else if (e.key === "ArrowLeft" || e.key === "PageUp") {
        e.preventDefault();
        handlePageChange(currentPage - 1);
      } else if (e.key === "Home") {
        e.preventDefault();
        handlePageChange(1);
      } else if (e.key === "End") {
        e.preventDefault();
        handlePageChange(totalPages);
      } else if (e.ctrlKey && e.key === "f") {
        e.preventDefault();
        setIsSearchOpen(true);
      } else if (e.key === "Escape") {
        setIsSearchOpen(false);
        setActiveTool(null);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [currentPage, totalPages]);

  useEffect(() => {
    if (activeTool) {
      const handleMouseUp = () => {
        setTimeout(handleTextSelection, 10);
      };
      document.addEventListener("mouseup", handleMouseUp);
      return () => document.removeEventListener("mouseup", handleMouseUp);
    }
  }, [activeTool, activeColor, currentPage]);

  useEffect(() => {
    const section = sampleDocument.sections[currentPage - 1];
    if (!section) {
      return;
    }

    const now = Date.now();
    const previous = sectionTimerRef.current;
    if (previous && previous.sectionId !== section.id && flushSectionInteractionRef.current) {
      void flushSectionInteractionRef.current(previous.sectionId, now - previous.start);
    }
    sectionTimerRef.current = { sectionId: section.id, start: now };
  }, [currentPage]);

  useEffect(() => {
    return () => {
      if (sectionTimerRef.current && flushSectionInteractionRef.current) {
        const { sectionId, start } = sectionTimerRef.current;
        void flushSectionInteractionRef.current(sectionId, Date.now() - start);
      }
    };
  }, []);

  useEffect(() => {
    const section = sampleDocument.sections[currentPage - 1];
    if (!section) {
      return;
    }

    if (!requestedRecommendationsRef.current.has(section.id)) {
      requestedRecommendationsRef.current.add(section.id);

      let cancelled = false;
      (async () => {
        try {
          const history = sessionHistory
            .filter((interaction) => interaction.sectionId === section.id)
            .map((interaction) => ({
              sectionId: interaction.sectionId,
              formatUsed: interaction.formatUsed,
              timeSpentMs: interaction.timeSpentMs,
              quizScore: interaction.quizScore,
              completed: interaction.completed,
            }));

          const metadata = {
            ...SECTION_METADATA[section.id],
            length: SECTION_METADATA[section.id]?.length ?? section.content.length,
          };

          const response = await api.analyzeLearningFormat({
            sectionId: section.id,
            sectionTitle: section.title,
            sectionContent: section.content,
            contentMetadata: metadata,
            studentHistory: history,
          });

          if (!cancelled) {
            setRecommendations((prev) => {
              const map = new Map(prev);
              map.set(section.id, response);
              return map;
            });
          }
        } catch (error) {
          console.error("Failed to analyze learning format", error);
          requestedRecommendationsRef.current.delete(section.id);
        }
      })();

      return () => {
        cancelled = true;
      };
    }
  }, [currentPage]);

  useEffect(() => {
    const section = sampleDocument.sections[currentPage - 1];
    if (!section) {
      return;
    }

    const recommendation = recommendations.get(section.id);
    if (!recommendation) {
      return;
    }

    if (recommendation.format === "text") {
      updateFormatUsageValue(section.id, "text");
      return;
    }

    if (autoGeneratedSectionsRef.current.has(section.id)) {
      return;
    }

    if (mediaItems.has(section.id)) {
      autoGeneratedSectionsRef.current.add(section.id);
      return;
    }

    autoGeneratedSectionsRef.current.add(section.id);

    if (recommendation.format === "visual") {
      void handleMediaAdd(section.id, "image");
    } else if (recommendation.format === "audio") {
      void handleMediaAdd(section.id, "audio");
    } else if (recommendation.format === "multimodal") {
      void handleMediaAdd(section.id, "multimodal");
    }
  }, [currentPage, recommendations, handleMediaAdd, mediaItems, updateFormatUsageValue]);

  return (
    <div className="h-screen flex flex-col" data-testid="reader-page">
      <Toolbar
        currentPage={currentPage}
        totalPages={totalPages}
        zoom={zoom}
        isSidebarOpen={isSidebarOpen}
        onPageChange={handlePageChange}
        onZoomChange={handleZoomChange}
        onToggleSidebar={() => setIsSidebarOpen(!isSidebarOpen)}
        onSearchToggle={() => setIsSearchOpen(!isSearchOpen)}
        onAnnotateToggle={() => setIsAnnotateMode(!isAnnotateMode)}
      />

      {isSearchOpen && (
        <SearchPanel
          onSearch={setSearchQuery}
          onClose={() => {
            setIsSearchOpen(false);
            setSearchQuery("");
          }}
          totalResults={totalSearchResults}
          currentResult={currentSearchResult}
          onNextResult={handleNextSearchResult}
          onPrevResult={handlePrevSearchResult}
        />
      )}

      {isAnnotateMode && (
        <AnnotationToolbar
          activeTool={activeTool}
          activeColor={activeColor}
          onToolChange={setActiveTool}
          onColorChange={setActiveColor}
        />
      )}

      <div className="flex-1 flex overflow-hidden">
        <TextViewer
          sections={sampleDocument.sections}
          currentPage={currentPage}
          zoom={zoom}
          searchQuery={searchQuery}
          currentSearchResult={currentSearchResult}
          annotations={annotations}
          mediaItems={mediaItems}
          quiz={sampleDocument.quiz}
          onPageChange={handlePageChange}
          onSearchMatchesFound={handleSearchMatchesFound}
          onMediaAdd={handleMediaAdd}
          onMediaRemove={handleMediaRemove}
          aiRecommendation={
            currentSection && currentRecommendation
              ? {
                  sectionId: currentSection.id,
                  format: currentRecommendation.format,
                  reasoning: currentRecommendation.reasoning,
                  confidence: currentRecommendation.confidence,
                }
              : undefined
          }
          activeSectionId={currentSection?.id ?? 0}
          onQuizSubmit={({ score, sectionId }) => handleQuizSubmit(sectionId, score)}
        />

        {isSidebarOpen && (
          <Sidebar
            annotations={annotations}
            bookmarks={bookmarks}
            notes={notes}
            onAnnotationClick={handleAnnotationClick}
            onBookmarkClick={handleBookmarkClick}
            onAnnotationDelete={handleAnnotationDelete}
            onBookmarkDelete={handleBookmarkDelete}
            onBookmarkAdd={handleBookmarkAdd}
            onNoteUpdate={handleNoteUpdate}
          />
        )}
      </div>
    </div>
  );
}
